// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnSi5iAvBRCxUFrVQ3PKkgY0qUELzbHrM',
    appId: '1:619920562964:web:e791039c2f88d5c6674001',
    messagingSenderId: '619920562964',
    projectId: 'empire-furniture-city-a1fa9',
    authDomain: 'empire-furniture-city-a1fa9.firebaseapp.com',
    storageBucket: 'empire-furniture-city-a1fa9.appspot.com',
    measurementId: 'G-KKH5RTL1F6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK4PtHcNGE-s-li8UJSV0cQFcvI9wR2wM',
    appId: '1:619920562964:android:1c5a735e20bbc3a0674001',
    messagingSenderId: '619920562964',
    projectId: 'empire-furniture-city-a1fa9',
    storageBucket: 'empire-furniture-city-a1fa9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9QjVaaoM1QjjqSMTGaHMuBOj-Fhx0mmM',
    appId: '1:619920562964:ios:0aac0b1bf2e2d4ea674001',
    messagingSenderId: '619920562964',
    projectId: 'empire-furniture-city-a1fa9',
    storageBucket: 'empire-furniture-city-a1fa9.appspot.com',
    iosClientId: '619920562964-r1bm2bu1bigm0q8me4veqsrvfkfj9ejo.apps.googleusercontent.com',
    iosBundleId: 'com.example.empireFurnitureCity',
  );
}
